Fix bug in isTrackingValues function.
Was causing this error when using the select component in certain ways:
`Uncaught (in promise) TypeError: this.$options.props.hasOwnProperty
is not a function`

See also: https://github.com/sagalbot/vue-select/issues/1251#issuecomment-856389680

This just reverts a change from a Vue 3 compatibility PR that was
made to vue-select.